// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: kernel/transport/protocol/auth.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Internal []byte `protobuf:"bytes,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Flag     uint32 `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Key      string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ClientAuth) Reset() {
	*x = ClientAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kernel_transport_protocol_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuth) ProtoMessage() {}

func (x *ClientAuth) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_transport_protocol_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuth.ProtoReflect.Descriptor instead.
func (*ClientAuth) Descriptor() ([]byte, []int) {
	return file_kernel_transport_protocol_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ClientAuth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientAuth) GetInternal() []byte {
	if x != nil {
		return x.Internal
	}
	return nil
}

func (x *ClientAuth) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *ClientAuth) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SessionAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MainHost []byte `protobuf:"bytes,2,opt,name=mainHost,proto3" json:"mainHost,omitempty"`
	SubHost  []byte `protobuf:"bytes,3,opt,name=subHost,proto3" json:"subHost,omitempty"`
}

func (x *SessionAuth) Reset() {
	*x = SessionAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kernel_transport_protocol_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAuth) ProtoMessage() {}

func (x *SessionAuth) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_transport_protocol_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAuth.ProtoReflect.Descriptor instead.
func (*SessionAuth) Descriptor() ([]byte, []int) {
	return file_kernel_transport_protocol_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SessionAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionAuth) GetMainHost() []byte {
	if x != nil {
		return x.MainHost
	}
	return nil
}

func (x *SessionAuth) GetSubHost() []byte {
	if x != nil {
		return x.SubHost
	}
	return nil
}

var File_kernel_transport_protocol_auth_proto protoreflect.FileDescriptor

var file_kernel_transport_protocol_auth_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x62, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41,
	0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x69,
	0x6e, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x61, 0x69,
	0x6e, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x48, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x75, 0x62, 0x48, 0x6f, 0x73, 0x74, 0x42,
	0x26, 0x5a, 0x24, 0x2e, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kernel_transport_protocol_auth_proto_rawDescOnce sync.Once
	file_kernel_transport_protocol_auth_proto_rawDescData = file_kernel_transport_protocol_auth_proto_rawDesc
)

func file_kernel_transport_protocol_auth_proto_rawDescGZIP() []byte {
	file_kernel_transport_protocol_auth_proto_rawDescOnce.Do(func() {
		file_kernel_transport_protocol_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_kernel_transport_protocol_auth_proto_rawDescData)
	})
	return file_kernel_transport_protocol_auth_proto_rawDescData
}

var file_kernel_transport_protocol_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kernel_transport_protocol_auth_proto_goTypes = []interface{}{
	(*ClientAuth)(nil),  // 0: protocol.ClientAuth
	(*SessionAuth)(nil), // 1: protocol.SessionAuth
}
var file_kernel_transport_protocol_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kernel_transport_protocol_auth_proto_init() }
func file_kernel_transport_protocol_auth_proto_init() {
	if File_kernel_transport_protocol_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kernel_transport_protocol_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kernel_transport_protocol_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kernel_transport_protocol_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kernel_transport_protocol_auth_proto_goTypes,
		DependencyIndexes: file_kernel_transport_protocol_auth_proto_depIdxs,
		MessageInfos:      file_kernel_transport_protocol_auth_proto_msgTypes,
	}.Build()
	File_kernel_transport_protocol_auth_proto = out.File
	file_kernel_transport_protocol_auth_proto_rawDesc = nil
	file_kernel_transport_protocol_auth_proto_goTypes = nil
	file_kernel_transport_protocol_auth_proto_depIdxs = nil
}
