// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: kernel/transport/protocol/packet.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len      []byte `protobuf:"bytes,1,opt,name=len,proto3" json:"len,omitempty"`
	Rid      uint32 `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Protocol []byte `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *PacketHeader) Reset() {
	*x = PacketHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kernel_transport_protocol_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketHeader) ProtoMessage() {}

func (x *PacketHeader) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_transport_protocol_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketHeader.ProtoReflect.Descriptor instead.
func (*PacketHeader) Descriptor() ([]byte, []int) {
	return file_kernel_transport_protocol_packet_proto_rawDescGZIP(), []int{0}
}

func (x *PacketHeader) GetLen() []byte {
	if x != nil {
		return x.Len
	}
	return nil
}

func (x *PacketHeader) GetRid() uint32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *PacketHeader) GetProtocol() []byte {
	if x != nil {
		return x.Protocol
	}
	return nil
}

var File_kernel_transport_protocol_packet_proto protoreflect.FileDescriptor

var file_kernel_transport_protocol_packet_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x22, 0x4e, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6c, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x42, 0x26, 0x5a, 0x24, 0x2e, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_kernel_transport_protocol_packet_proto_rawDescOnce sync.Once
	file_kernel_transport_protocol_packet_proto_rawDescData = file_kernel_transport_protocol_packet_proto_rawDesc
)

func file_kernel_transport_protocol_packet_proto_rawDescGZIP() []byte {
	file_kernel_transport_protocol_packet_proto_rawDescOnce.Do(func() {
		file_kernel_transport_protocol_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_kernel_transport_protocol_packet_proto_rawDescData)
	})
	return file_kernel_transport_protocol_packet_proto_rawDescData
}

var file_kernel_transport_protocol_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kernel_transport_protocol_packet_proto_goTypes = []interface{}{
	(*PacketHeader)(nil), // 0: protocol.PacketHeader
}
var file_kernel_transport_protocol_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kernel_transport_protocol_packet_proto_init() }
func file_kernel_transport_protocol_packet_proto_init() {
	if File_kernel_transport_protocol_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kernel_transport_protocol_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kernel_transport_protocol_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kernel_transport_protocol_packet_proto_goTypes,
		DependencyIndexes: file_kernel_transport_protocol_packet_proto_depIdxs,
		MessageInfos:      file_kernel_transport_protocol_packet_proto_msgTypes,
	}.Build()
	File_kernel_transport_protocol_packet_proto = out.File
	file_kernel_transport_protocol_packet_proto_rawDesc = nil
	file_kernel_transport_protocol_packet_proto_goTypes = nil
	file_kernel_transport_protocol_packet_proto_depIdxs = nil
}
